### ISSUE TITLE
Add support for Radar Geocoding

### ISSUE THREAD

**Issue by ollie10** [JustinCanton/Geo.NET#100]
Hello @JustinCanton , I saw various enhancements about adding new providers, so if I can suggest one, I would suggest [Radar](https://radar.com/). They have well-written [APIs](https://radar.com/documentation/api), which works pretty well, and a [free tier of 100.000 calls a month](https://radar.com/pricing).

Cheers

**Comment by JustinCanton** [comment]
Hi @ollie10, thank you for the suggestion! They look like a good provider with clear documentation. I will add them into the roadmap and hopefully have support for them soon.
