### ISSUE TITLE
"CntryName" field missing from findAddressCandidate response

### ISSUE THREAD

**Issue by benjburkholder** [JustinCanton/Geo.NET#113]
Hello!

Noticed while using AddressCandidateAsync() that the return is missing the field "CntryName" which can be found when querying ArcGIS' findAddressCandidates api.

Even when included in the outFields param, this field does not appear to be present in the result set. 

For example, in my outField string when using this package, both Country and CntryName are present in outField string:

`LongLabel,ShortLabel,Addr_type,Type,PlaceName,Place_addr,Phone,URL,AddBldg,AddNum,AddNumFrom,AddNumTo,AddRange,Side,StPreDir,StPreType,StName,StType,StDir,BldgType,BldgName,LevelType,LevelName,UnitType,UnitName,SubAddr,StAddr,Block,Sector,Nbrhd,District,City,MetroArea,Subregion,Region,RegionAbbr,Territory,Zone,Postal,PostalExt,Country,CntryName,LangCode,Distance,X,Y,DisplayX,DisplayY,Xmin,Xmax,Ymin,Ymax,ExInfo`

However, in the return, "Country" is set to the three digit country code, and "CountryCode" is null. Meanwhile "CntryName" is not present in any form.

![Screenshot 2024-09-24 124729](https://github.com/user-attachments/assets/efa30e47-d05c-4a51-baa0-58016aefe9ba)

When I query the ArcGIS _findAddressCandidates_ api, with the same outField params, I get the "CntryName" field back.
![Screenshot 2024-09-24 130604](https://github.com/user-attachments/assets/d658a541-38e1-442c-a2c3-7ad9e0ee2ebe)

Thanks!

**Comment by JustinCanton** [comment]
Sorry for the long delay on this one, @benjburkholder. I have a PR open for it, and will be merging it soon. You will have an alpha build for it soon.

The release for 2.1.2 will be out soon.

**Comment by benjburkholder** [comment]
@JustinCanton thank you!
