### ISSUE TITLE
Merge enhancement from v2.2.0-alpha.1 into 2.1.2

### ISSUE THREAD

**Issue by benjburkholder** [JustinCanton/Geo.NET#120]
After testing out v2.1.2, it looks like it does not include the previous enhancement we pushed up (and was implemented) in order to give the user the ability to specify the 'outFields' to get back in the findAddressCandidates request, it was released as version 2.2.0-alpha.1.

Are we able to get this enhancement added to the new version 2.1.2? Or, if you don't want this functionality to be part of a main release, then add this bugfix to the alpha version so both updates are in the same release? https://github.com/JustinCanton/Geo.NET/issues/113 

Here is the original PR for reference: https://github.com/JustinCanton/Geo.NET/pull/107/files.

Thanks!

**Comment by JustinCanton** [comment]
Hello @benjburkholder,

The 2.1.2 release is already out. It was a patch, meaning only bugfixes. So the enhancement for the outFields would not be included in it.

But if you want to test out both the bug fix and the enhancement, you can use the 2.2.0-alpha version like you mentioned. A new nuget, 2.2.0-alpha.12, was released a week ago with both changes in it.

I am hoping to have a full 2.2.0 release in the next month, so you will be able to use a full release version relatively soon.

Let me know if you have any more questions.

Thank you,
Justin

**Comment by benjburkholder** [comment]
@JustinCanton Ah okay I was unaware of an accompanying new alpha release, this is working as expected. I'll keep an eye out for the 2.2.0 release as well.

Many thanks!
