### ISSUE TITLE
Missing parameters in Bing Maps

### ISSUE THREAD

**Issue by ollie10** [JustinCanton/Geo.NET#82]
Hi @JustinCanton

As told before I will report you missing parameters, in the case of [Bing Maps REST Service](https://learn.microsoft.com/en-us/bingmaps/rest-services/).

I saw that the most important is the [culture ](https://learn.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/culture-parameter) which is missing, but if you want a view of what's missing i think [here you have the list](https://learn.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/)

Many thanks

**Comment by JustinCanton** [comment]
@ollie10 , checking the list, the only real parameter missing is the culture. The output parameters [here](https://learn.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/output-parameters) are internal concerns for the nuget, so I don't really need to worry about those. I am updating the code now.
