### ISSUE TITLE
Wrong 'in' parameter in Here Maps

### ISSUE THREAD

**Issue by ollie10** [JustinCanton/Geo.NET#87]
Hey @JustinCanton,

I was just switching to your latest version and my unit tests already spotted an error.

In Here Maps you are passing the 'in' parameters in this way:
`https://geocode.search.hereapi.com/v1/geocode?q=31 Hills Point Road, Charlotte&in=USA&limit=1&lang=es-ES&show=countryInfo,streetInfo&apiKey=xxx`

But according to [their documentation](https://developer.here.com/documentation/geocoding-search-api/api-reference-swagger.html) you should use:

`countryCode:USA
OR
countryCode:CAN,MEX,USA`

I used the exception data as you told me the other time and this is what I saw:

`{"status":400,"title":"Illegal input for parameter 'in'","cause":"Actual parameter value: 'USA'","action":"Unsupported key: 'USA'. Supported keys: 'countryCode'","correlationId":"fa73fe06-133b-4aaf-b654-e9c75177e7ac","requestId":"REQ-c5ae3f1b-3231-4f50-8cb7-15f0277af84c"}`

Do you think it will be fast to fix and redeploy to nuget?
Many thanks!

**Comment by JustinCanton** [comment]
Hello @ollie10 ,

Interesting. I will need to look into this a bit. It hopefully shouldn't take too long to fix this. I will make a hotfix for this issue.

Justin

**Comment by ollie10** [comment]
Ok, this is the part involved: [https://ibb.co/VLF53vx](https://ibb.co/VLF53vx)

**Comment by JustinCanton** [comment]
@ollie10, this issue is fixed in the 1.5.2 release. Let me know if there are any more issue.

Justin
